---
kind: Service
apiVersion: v1
metadata:
  name: mnist-service
  labels:
    app: mnist-service
spec:
  ports:
  - port: 8080
    targetPort: mms
  selector:
    app: mnist-service
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mnist-service
  labels:
    app: mnist-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-service
  template:
    metadata:
      labels:
        app: mnist-service
    spec:
      containers:
      - name: mnist-service
        image: rgaut/deeplearning-mxnet:inference
        args:
        - mxnet-model-server
          --start
          --model-store /home/model-server/archived_model
          --models mnist=mnist_cnn.mar
        ports:
        - name: mms
          containerPort: 8080
        - name: mms-management
          containerPort: 8081
        imagePullPolicy: IfNotPresent